### ISSUE TITLE
Dom fromString could leverage createContextualFragment

### ISSUE THREAD

**Issue by schallm** [dojo/dom#21]
Looks like most modern browsers support it. We would still need to fall back to current code for older browsers. 

https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment

**Comment by kfranqueiro** [comment]
I presume you're suggesting this could replace the tag-wrapping functionality?  What are your expectations of how this would work, given that `fromString` doesn't currently require a context?

**Comment by schallm** [comment]
The way I read the doc, it is supposed to be a "better" innerHTML?  Is context the only thing it gives?

**Comment by kfranqueiro** [comment]
My point is, it requires a range, which would need to be built from...something.  `dom.fromString` only takes a string of HTML as input - there is nothing in its current API to build a range from.

The MDN article doesn't provide a particularly clear understanding of what advantages this API gives.  Have you experimented with it at all?  We would need to do so in order to evaluate if it's even worth considering.  My current inclination would be to pass on it, given the need for an additional input parameter and the fact it won't work in all browsers anyway (and trying to make fallback code work consistently with it would likely require additional effort as well).

**Comment by schallm** [comment]
I have not used the api so I don't know specifics.  I just read about it on Twitter myself and thought of dom-construct.  I thought dojo 2 was in the research phase and wanted to offer a suggestion.  

FWIW:  createRange is a function off document so one could be created the same way the current function uses the document object to create the wrapping div element.

**Comment by kitsonk** [comment]
@schallm I don't think the feedback was at all to discourage contribution.  I think @kfranqueiro thought that you might have had some experience with it, which would have been very useful in figuring out if it fits into Dojo 2.  The challenge with "most browsers" is that you then have to figure out how to make the consumable API transparent to that fact and then it depends on the upside of how much better it makes it.  I think Ken's initial feeling is that it might not be worth the additional complexity (of the context) and I suspect it would be a priority for the initial release, but could easily be looked at if someone had the desire.

**Comment by vansimke** [comment]
I spun up a quick benchmark test to compare the current `fromString` implementation with a quick-and-dirty version using `createContextualFragment`. Performance on Chrome 48 on OS X led to a performance boost of about 140% (about 2.4x faster). Given this initial evidence, this seems like it would be worth pursuing further. I'm planning on building out the rest of the `fromString`'s functionality to ensure that this is a true apples-to-apples comparison. If performance advantages continue to be evident, then I can extend the tests out to cover multiple browsers.

**Comment by vansimke** [comment]
Including the initial benchmark test to let others review it.

```javascript
import registerSuite = require('intern!object');

import * as dom from 'src/dom';

let html = '';
const numIterations = 5000;
const numElements = 500;

registerSuite({
	name: 'fromString Benchmark',

	setup: function() {
		for (let i = 0; i < numElements; i++) {
			html += '<div>Hello</div>';
		}
	},

	fromString: function() {
		const start = performance.now();

		for (let i = 0; i < numIterations; i++) {
			dom.fromString(html);
		}

		console.log('fromString: ' + (performance.now() - start));

	},

	createContexturalFragment: function() {
		const start = performance.now();

		for (let i = 0; i < numIterations; i++) {
			const range = document.createRange();
			range.createContextualFragment(html);
		}

		console.log('createContextualFragment: ' + (performance.now() - start));
	}
});
```

**Comment by kfranqueiro** [comment]
I'd be interested to see what differences from the current implementation (which is largely based on Dojo 1's) `createContextualFragment` shows in actual behavior for various types of elements.  A good start would be to run an implementation relying on it through our existing `fromString` unit tests to see what happens.

**Comment by vansimke** [comment]
I've been kicking this around and I have an implementation that passes all of the unit tests and still yields performance improvements of 25 - 300% when testing on various browsers using the test benchmark test similar to that above (OS X - Chrome, Safari, Firefox, Windows 8.1 - Chrome, IE11, Firefox).

The code is below, but there is one downside. In order for a Range object to be attached to a node, that node must be part of the page. This is part of the test code, but it could produce unexpected behaviors in applications that are sensitive to the DOM structure changing. 

```javascript
export function fromString(html: string): DocumentFragment {

	html = String(html);

	const match = html.match(/<\s*([\w\:]+)/);
	const tag = match ? match[1].toLowerCase() : '';
	let master: HTMLElement = document.createElement('div');
	document.body.appendChild(master);
	let range = document.createRange();
	range.selectNode(master);
	let fragment: DocumentFragment;
	if (match && tagWrap[tag]) {
		let wrap = tagWrap[tag];

		html = wrap.pre + html + wrap.post;
		fragment = range.createContextualFragment(html);
		for (let i = wrap.length; i--; ) {
			fragment = <HTMLElement> fragment.firstChild;
		}
	}
	else {
		fragment = range.createContextualFragment(html);
	}

	master.parentElement.removeChild(master);

	return fragment;
}
```

At this point, I'm looking for direction. Do we think this makes sense to implement? It would probably require an additional "has" test and a new branch in the fromString code to manage if the browser supports Ranges or not.

@kitsonk or @kfranqueiro do you have any thoughts?

**Comment by kitsonk** [comment]
@vansimke I think it makes sense to implement.  Is the PR you have open covering this off or do you need to issue another PR?

**Comment by vansimke** [comment]
PR #37 does reflect my proposed fix. I'll go through the comments and clean it up and then it should be all set.
