### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by eheasley** [dojo/dom#22]
Please confirm the README is updated and accurate for this repository.

**Comment by kfranqueiro** [comment]
When we work on this, we should be sure to document the current behavior of `deletate`'s selectors with regard to exclusion of the delegation root, as discussed in #25.

**Comment by baw** [comment]
I made a couple some changes in https://github.com/baw/dojo-dom/tree/update-readme

I was also looking into ways to have runnable examples of the modules/functions.
