### ISSUE TITLE
Supporting Android

### ISSUE THREAD

**Issue by kitsonk** [dojo/dom#32]
Currently there are some test [failures on Android](https://travis-ci.org/dojo/dom/builds/99278518#L303) and ideally dojo/dom should support Android.

**Comment by kfranqueiro** [comment]
I suspect the delegate failures could be due to #26.  I guess maybe we need that code after all.  At the time I'd run it, I wasn't testing mobile.

Also I'm not sure why or if it's temporary or just me, but it seems like I can't view changesets on this github repository right now...

**Comment by kitsonk** [comment]
Yeah, it seems to be a github issue... we ran into it on other repos recently as well.

**Comment by vansimke** [comment]
updated commit message per feedback from @kfranqueiro
