### ISSUE TITLE
Upgrade to TypeScript 1.8.7 and add dojo-core dependency

### ISSUE THREAD

**Issue by kitsonk** [dojo/dom#39]
A couple updates to this package we should do:

- [ ] We should upgrade to TypeScript 1.8.7.
- [ ] We can now drop the `_modules/dojo-core` and instead add a `peerDependency` for `dojo-core`.

**Comment by kfranqueiro** [comment]
How much of this does #33 already cover?

**Comment by kitsonk** [comment]
All of it (except 1.8.2 instead of 1.8.7), but I forgot I had already issued the PR.
