### ISSUE TITLE
dojoReady?

### ISSUE THREAD

**Issue by taoqf** [dojo/dom#48]
in which packge can i find this?
i find it in dojo/dojo2 which says`This repository is not part of what will become Dojo 2. We are not looking for contributions to this repository. If you wish to use or contribute to Dojo 2, please visit dojo/meta to find more information on the current status and packages of Dojo 2`

**Comment by kitsonk** [comment]
Issue moved to [dojo/meta #41](https://github.com/dojo/meta/issues/41) via [**ZenHub.io**](https://www.zenhub.io/)
