### ISSUE TITLE
Implement dom.addCssRule

### ISSUE THREAD

**Issue by eheasley** [dojo/dom#5]
This is roughly equivalent to `dgrid/util/misc.addCssRule`, with `remove` renamed to `destroy` for consistency with other APIs, and a new `remove` added to remove specific styles (to round out `get` and `set`).

[dom Proposal Reference](https://docs.google.com/document/d/1fXGrlsl3aTqst7mCj3XqlKdbuCJs4rB9r7qIxC-tWMQ/edit#heading=h.bn74nbxadwwa)

**Comment by kfranqueiro** [comment]
Whoops, neither of us remembered to reference this issue in the pull request or commit (I referenced the PR number but not this one).  This has been resolved via #6.
