### ISSUE TITLE
Future of dojo/dom

### ISSUE THREAD

**Issue by dylans** [dojo/dom#64]
In a virtual DOM world, dojo/dom may not have much of a future unless it was intended to be the foundation for a virtual DOM implementation. Given that we rely on Maquette, that seems less important.

Looking at dojo/dom, it contains the following capabilities:

* CSS rule addition/manipulation against the CSSOM (rather than inline styles). This could still be useful, though it may make more sense to roll this into how we work with themes and scene management?
* Event delegation. Not useful for vdom
* DOM node and css class CRUD. CSS class creation is probably redundant with capabilities in dojo/widget-core. Node creation/manipulation is redundant with capabilities from Maquette
* Form management (read all form field values)... should probably have something that works with widgets instead, will become redundant
* Feature testing, if a feature test passes, add a CSS class to top level node. Presumably used for working around quirks. Not sure if this is useful and if so where it should live.
* DOM batch operations, sort of a very primitive first step towards vdom, though really more of a queue/RAF manager. Probably not useful for Dojo 2 users.

The only reason to consider keeping DOM node CRUD, event delegation, form management, and DOM batch operations would be as a way to introduce people to Dojo 2 that are building simple websites and just need a few fixes to the DOM. This is pretty counter to the focus of Dojo 2, so it's probably not worth having.

So I see three possible outcomes:

1. Deprecate this package and find a better home for each feature that is needed for Dojo 2
2. Prune the package into just the things needed for Dojo 2
3. Move the features needed for Dojo 2 widgets elsewhere, keep a small set of DOM APIs here in case people need them.

In the case of outcomes 2 and 3, we need a code review/update for more recent improvements to TS.

**Comment by dylans** [comment]
@rishson assigned to you to add a deprecation warning, and address the original content of this ticket.

**Comment by kitsonk** [comment]
We have officially deprecated this package and all functionality is addressed one way or another in other packages or modules.
